name: My CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    services:
      db:
        image: postgres:16
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: run lint
        run: make lint
      - name: run test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: False
        run: |
          make setup
          make test
